### ISSUE TITLE
** operation not allowed

### ISSUE THREAD

**Issue by FedericoCapaldo** [digitaledgeit/npm-recursive-uglifyjs#1]
I tried to have a simple function 

`function xToY(x, y) {
  return (x ** y);
}`

but the operation does not seem to allowed.

**Comment by jameslnewell** [comment]
The `**` operator is ES7. The version of `uglify` used only supports ES5. I'm not sure if the version of `uglify` for ES6 is stable yet, let alone ES7. 

You're welcome to PR the new version of `uglify` but I'd recommend transpiling for now.
